import os
from dotenv import load_dotenv


load_dotenv()

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
CHROMEDRIVER_PATH = os.getenv("CHROMEDRIVER_PATH")
SOURCE_USDT_FASTEX_USDT = os.getenv("SOURCE_USDT_FASTEX_USDT")
SOURCE_USDT_BINANCE = os.getenv("SOURCE_USDT_BINANCE")
SOURCE_USDT_OKX = os.getenv("SOURCE_USDT_OKX")
SOURCE_FASTEX_BTC_USDT = os.getenv("SOURCE_FASTEX_BTC_USDT")
SOURCE_BINANCE_BTC_USDT = os.getenv("SOURCE_BINANCE_BTC_USDT")